# Generated by Django 4.2.7 on 2023-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openid", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("avatar", models.CharField(max_length=255)),
            ],
        ),
    ]
